config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update] do
    member do
      get :result
    end
  end
  resources :groups do
    collection do
      get :search
    end
    member do
      get :join
      delete :withdrawal
      delete :withdrawal_member
    end
  end
  resources :questions, only: %i[new]
  resources :password_resets, only: %i[new create edit update]
  resources :year_questions, only: %i[index]
  resources :category_questions, only: %i[index]
  resources :results, only: [:index, :show, :create]
  resources :contacts, only: [:new, :create]
  resources :question_papers, only: [:update]
  resources :papers do
    member do
      get :result
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :avatar, GroupImageUploader

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :owner_id, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_params, only: [:edit, :update, :destroy, :withdrawal]
  before_action :set_q, onlt: [:index, :search]
  def index
    @groups = Group.all.order(name: :asc).page(params[:page])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      # binding.pry
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group.destroy!
    redirect_to groups_path
  end

  def join
    @group = Group.find_by(id: params[:id])
    if !@group.users.include?(current_user)
      @group.users << current_user
      redirect_to group_path
    end
  end

  def withdrawal
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def withdrawal_member
    @group_user = GroupUser.find_by(user_id: params[:user_id],group_id: params[:id])
    @group_user.destroy
    redirect_back fallback_location: root_path
  end

  def search
    @results = @q.result
  end

  private
  def group_params
    params.require(:group).permit(:name, {:user_ids => []}, :avatar, :avatar_cache)
  end
  
  def set_params
    @group = Group.find(params[:id])
  end

  def set_q
    @q = Group.ransack(params[:q])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_crud_menus.html.erb
<% if current_user.own?(group) || current_user.admin? %>
  <div class="flex">
    <div class="px-1">
      <%= link_to "編集", edit_group_path(group),class:"btn btn-primary " %>
    </div>
    <div class="px-1">
      <%= link_to "削除", group_path(group), method: :delete,class:"btn btn-danger", data: {confirm: "グループを削除しますか？"} %>
    </div>
  </div>
  <br>
<% end %>

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3', accept: 'image/*' %>
    <%= f.hidden_field :avatar_cache %>
  </div>
  <br>
  <div class='mt-3 mb-3'>
    <%= image_tag @group.avatar.url, class: 'rounded-circle', id: 'preview', size: '100x100' %>
  </div>
  <%= f.submit (t 'defaults.register'), class: 'btn btn-primary' %>
<% end %>

app/views/groups/edit.html.erb
<div class="md:text-4xl text-3xl text-center">
  <h1><%= t '.title' %></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      
      <%= render partial: 'form', locals: { group: @group } %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="w-4/5 container mx-auto">
  <div class="flex justify-center md:text-4xl text-3xl font-extrabold mt-2 mb-4">
    <h1>グループ一覧ページ</h1>
  </div>
  <div>
    <%= search_form_for @q, url: search_groups_path do |f| %>
      <%= f.search_field :name_cont, class: "container mx-auto bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-1/2 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      <div class="text-center">
        <%= f.submit '検索', class: "inline-block bg-gray-700 text-white px-2 py-1 mt-1 rounded-md" %>
      </div>
    <% end %>
  </div>
  <% if !current_user.groups.present? %>
      <%= link_to "グループ作成", new_group_path, class: "btn btn-primary" %>
  <% end %>
  <% if @groups.present? %>
    <div class='col-md-10 offset-md-1'>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td>
              <%= link_to(group_path(group)) do %>
                <%= image_tag group.avatar.url, class: 'rounded-circle', size: '100x100' %>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to(group_path(group)) do %>
                <%= group.name %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>NO RESULT</p>
  <% end %>
  <div class="flex justify-center">
    <%= paginate @groups %>
  </div>
  <br>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t '.title' %></h1>
      <%= render partial: 'form', locals: { group: @group } %>
    </div>
  </div>
</div>

app/views/groups/search.html.erb
<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |group| %>
      <tr>
        <td><%= image_tag group.avatar.url, class: 'rounded-circle', size: '100x100' %></td>
        <td><%= link_to group.name, group_path(group) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Top', groups_path %>

app/views/groups/show.html.erb
<div class="w-4/5 container mx-auto">
  <div>
    <br>
    <h1 class="flex justify-center text-4xl font-extrabold mt-2 mb-4"><%= @group.name %></h1>
    <div class="flex justify-between">
      <% if !GroupUser.exists?(user_id: current_user.id) %>
        <div>
          <%= link_to '参加する', join_group_path(@group), class:"btn btn-primary" %>
        </div>
      <% elsif GroupUser.exists?(group_id: @group.id, user_id: current_user.id) %>
        <div>
            <%= link_to '退会する', withdrawal_group_path(@group), method: :delete, class:"btn btn-danger", data: {confirm: "退会しますか？"} %>
        </div>
      <% end %>
      <div> 
        <%= render partial: 'crud_menus', locals: { group: @group } %>
      </div>
    </div>
    <div>
      <div class="flex flex-wrap justify-center">
        <%= image_tag @group.avatar.url, class: 'rounded-circle', size: '150x150' %>
      </div>
      <br>
      <p class="text-2xl text-center border-solid border-bottom font-bold pb-2">メンバー</p>
      <br>
      <div class="flex flex-wrap">
        <% @group.users.each do |group_user| %>
        <div class="rounded border p-3 w-1/2 text-center px-4">
          <%= link_to group_user.decorate.full_name, user_path(group_user) %>
          <% if current_user.admin? || current_user.id == group_user.id %>
              <%= link_to "強制退会", withdrawal_member_group_path(user_id: group_user.id), method: :delete, class:"btn btn-danger text-sm", data: {confirm: "退会させますか？"} %>
          <% end %>
        </div>
          <br>
        <% end %>
      </div>
    </div>
  </div>
  <br>
</div>