config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update] do
    member do
      get :result
    end
  end
  resources :groups do
    collection do
      get :search
    end
    member do
      get :join
      delete :withdrawal
      delete :withdrawal_member
    end
  end
  resources :questions, only: %i[new]
  resources :password_resets, only: %i[new create edit update]
  resources :year_questions, only: %i[index]
  resources :category_questions, only: %i[index]
  resources :results, only: [:index, :show, :create]
  resources :contacts, only: [:new, :create]
  resources :question_papers, only: [:update]
  resources :papers do
    member do
      get :result
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    elsif user.general?
      can :manage, :all 
      cannot :access, :rails_admin
    else
      can :read, :all
      can :create, :user
      cannot :access, :rails_admin
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.simple_import(path: '', col_sep: ',')
    a = []
    CSV.foreach(path, headers: true, col_sep: col_sep) do |r|
      a << self.new(get_import_params(r))
    end
    import a # activerecord-importのメソッドです。
  end

  private
  def self.get_import_params(row)
    headers = row.headers & self.column_names # 存在するカラム名のみに限定する
    headers.each_with_object({}) do |c, h|
      h[c.to_sym] = row.field(c)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exams
  has_many :years, through: :exams
  validates :body, presence: true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question, dependent: :destroy
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :category
  belongs_to :year
  has_many :questions

  validates :title, presence: true

  enum exam_type: { otsu: 0, kou: 1 }
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :avatar, GroupImageUploader

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :owner_id, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :user

  has_many :question_papers, dependent: :destroy
  has_many :questions, through: :question_papers, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam
  has_many :choices, dependent: :destroy

  has_many :question_papers, dependent: :destroy
  has_many :papers, through: :question_papers, dependent: :destroy
end

app/models/question_paper.rb
class QuestionPaper < ApplicationRecord
  belongs_to :paper
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, UserImageUploader
  authenticates_with_sorcery!
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true
  validates :comment, length: { maximum: 255 }

  validates :email, uniqueness: true

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy

  has_many :papers

  enum role: { general: 0, admin: 1 }
  enum certification: { non: 0, otsu: 1, kou: 2 }

  def own?(object)
    id == object.owner_id
    # binding.pry
  end

  def my_group?(object)
    current_user.groups.id == object.id
  end

  def deliver_reset_password_instructions!
    mail = false
    config = sorcery_config
    # hammering protection
    return false if config.reset_password_time_between_emails.present? && send(config.reset_password_email_sent_at_attribute_name) && send(config.reset_password_email_sent_at_attribute_name) > config.reset_password_time_between_emails.seconds.ago.utc
  
    self.class.sorcery_adapter.transaction do
      generate_reset_password_token!
      mail = send_reset_password_email! unless config.reset_password_mailer_disabled
    end
    mail
  end

  def load_from_reset_password_token(token, &block)
    load_from_token(
      token,
      @sorcery_config.reset_password_token_attribute_name,
      @sorcery_config.reset_password_token_expires_at_attribute_name,
      &block
    )
  end

  def change_password(new_password, raise_on_failure: false)
    clear_reset_password_token
    send(:"#{sorcery_config.password_attribute_name}=", new_password)
    sorcery_adapter.save raise_on_failure: raise_on_failure
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :exams
  has_many :categories, through: :exams
  validates :body, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_before_login_header.html.erb
<nav class="bg-indigo-700 border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
    <%= link_to root_path do %>
      <%= image_tag 'top-logo.png', :width => '500', :height => '150' %>
    <% end %>
    <div class="flex items-center lg:order-2">
      <div class="text-white text-opacity-75 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
        <%= link_to (t 'defaults.signup'), new_user_path, class: "hover:text-white" %>
      </div>
      <div class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
        <%= link_to (t 'defaults.login'), login_path, class: "hover:text-white" %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<div class = "bg-indigo-700">
  <div class="flex justify-around text-center m-3 w-4/5 container mx-auto">
    <div class="text-white text-opacity-75">
      <%= link_to "利用規約", page_path('terms_of_service'), class: "hover:text-white" %>
    </div>
    <div class="text-white text-opacity-75">
      <%= link_to "プライバシーポリシー", page_path('privacy_policy'), class: "hover:text-white" %>
    </div>
    <div class="text-white text-opacity-75">
      <%= link_to "お問い合わせ", page_path('form'), class: "hover:text-white" %>
    </div>
    <% if current_user.try(:admin?) %>
      <div class="text-white text-opacity-75">
        <%= link_to '管理者ページ', rails_admin_path, class: "hover:text-white" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
<nav class="bg-indigo-700 border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
    <%= link_to root_path do %>
      <%= image_tag 'top-logo.png', :width => '500', :height => '150' %>
    <% end %>
    <div class="flex items-center lg:order-2">
      <div class="text-white text-opacity-75 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
        <%= link_to (t 'defaults.group_search'), groups_path, class: "hover:text-white" %>
      </div>
      <div x-data="{ open: false }" class="dark:bg-gray-800 w-64 flex justify-center items-center">
        <div @click="open = !open" class="relative border-b-4 border-transparent py-3" :class="{'border-indigo-700 transform transition duration-300 ': open}" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100">
          <div class="flex justify-center items-center space-x-3 cursor-pointer">
            <div class="w-12 h-12 rounded-full overflow-hidden border-2 dark:border-white border-gray-900">
              <div class="w-full h-full object-cover">
                <%= image_tag current_user.avatar_url, size: '100x100', class: 'rounded-circle mr15'%>
              </div>
            </div>
            <div class="font-semibold dark:text-white text-gray-900 text-lg">
              <div class="cursor-pointer"><%= current_user.decorate.full_name %></div>
            </div>
          </div>
          <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute w-60 px-5 py-3 dark:bg-gray-800 bg-white rounded-lg shadow border dark:border-transparent mt-5">
            <ul class="space-y-3 dark:text-white">
              <li class="font-medium">
                <div class="flex items-center transform transition-colors duration-200 border-r-4 border-transparent hover:border-indigo-700">
                  <% if current_user.groups.present? %>
                    <% current_user.groups.each do |group| %>
                      <%= link_to group.name, group_path(group) %>
                    <% end %>
                  <% else %>
                    <p class = 'dropdown-item'>無所属</p>
                  <% end %>
                </div>
              </li>
              <li class="font-medium">
                <div class="flex items-center transform transition-colors duration-200 border-r-4 border-transparent hover:border-indigo-700">
                  <div class="mr-3">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
                  </div>
                  <div class="whitespace-no-wrap">
                    <%= link_to "アカウント", user_path(current_user) %>
                  </div>
                </div>
              </li>
              <hr class="dark:border-gray-700">
              <li class="font-medium">
                <div class="flex items-center transform transition-colors duration-200 border-r-4 border-transparent hover:border-indigo-700">
                  <div class="mr-3 text-red-600">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>
                  </div>
                  <div class="whitespace-no-wrap">
                    <%= link_to (t 'defaults.logout'), logout_path, method: :delete %>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>