config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update] do
    member do
      get :result
    end
  end
  resources :groups do
    collection do
      get :search
    end
    member do
      get :join
      delete :withdrawal
      delete :withdrawal_member
    end
  end
  resources :questions, only: %i[new]
  resources :password_resets, only: %i[new create edit update]
  resources :year_questions, only: %i[index]
  resources :category_questions, only: %i[index]
  resources :results, only: [:index, :show, :create]
  resources :contacts, only: [:new, :create]
  resources :question_papers, only: [:update]
  resources :papers do
    member do
      get :result
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    elsif user.general?
      can :manage, :all 
      cannot :access, :rails_admin
    else
      can :read, :all
      can :create, :user
      cannot :access, :rails_admin
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.simple_import(path: '', col_sep: ',')
    a = []
    CSV.foreach(path, headers: true, col_sep: col_sep) do |r|
      a << self.new(get_import_params(r))
    end
    import a # activerecord-importのメソッドです。
  end

  private
  def self.get_import_params(row)
    headers = row.headers & self.column_names # 存在するカラム名のみに限定する
    headers.each_with_object({}) do |c, h|
      h[c.to_sym] = row.field(c)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exams
  has_many :years, through: :exams
  validates :body, presence: true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question, dependent: :destroy
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :category
  belongs_to :year
  has_many :questions

  validates :title, presence: true

  enum exam_type: { otsu: 0, kou: 1 }
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :avatar, GroupImageUploader

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :owner_id, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :user

  has_many :question_papers, dependent: :destroy
  has_many :questions, through: :question_papers, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam
  has_many :choices, dependent: :destroy

  has_many :question_papers, dependent: :destroy
  has_many :papers, through: :question_papers, dependent: :destroy
end

app/models/question_paper.rb
class QuestionPaper < ApplicationRecord
  belongs_to :paper
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, UserImageUploader
  authenticates_with_sorcery!
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true
  validates :comment, length: { maximum: 255 }

  validates :email, uniqueness: true

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy

  has_many :papers

  enum role: { general: 0, admin: 1 }
  enum certification: { non: 0, otsu: 1, kou: 2 }

  def own?(object)
    id == object.owner_id
    # binding.pry
  end

  def my_group?(object)
    current_user.groups.id == object.id
  end

  def deliver_reset_password_instructions!
    mail = false
    config = sorcery_config
    # hammering protection
    return false if config.reset_password_time_between_emails.present? && send(config.reset_password_email_sent_at_attribute_name) && send(config.reset_password_email_sent_at_attribute_name) > config.reset_password_time_between_emails.seconds.ago.utc
  
    self.class.sorcery_adapter.transaction do
      generate_reset_password_token!
      mail = send_reset_password_email! unless config.reset_password_mailer_disabled
    end
    mail
  end

  def load_from_reset_password_token(token, &block)
    load_from_token(
      token,
      @sorcery_config.reset_password_token_attribute_name,
      @sorcery_config.reset_password_token_expires_at_attribute_name,
      &block
    )
  end

  def change_password(new_password, raise_on_failure: false)
    clear_reset_password_token
    send(:"#{sorcery_config.password_attribute_name}=", new_password)
    sorcery_adapter.save raise_on_failure: raise_on_failure
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :exams
  has_many :categories, through: :exams
  validates :body, presence: true
end

app/controllers/category_questions_controller.rb
class CategoryQuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_questions_helper.rb
module CategoryQuestionsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/category_questions/index.html.erb
<div class="w-4/5 container mx-auto">
  <div class="text-center md:text-6xl text-4xl font-extrabold font-serif mt-2 mb-4">
    <h1>過去問道場</h1>
  </div>
  <div class="text-center border-solid border-b-2 border-gray-600 pb-4">
    <div class="inline-block text-2xl">
      <%= link_to "年度別に問題を解く", year_questions_path, class: "mx-3" %>
    </div>
    <div class="border-solid border-b-2 border-blue-600 text-blue-600 mx-3 pb-1 inline-block text-2xl">
      <%= link_to "分野別に問題を解く", category_questions_path %>
    </div>
  </div>
  <div class="text-center mt-5 flex justify-evenly">
    <div>
      <div class="inline-block text-3xl">
        <h3>甲</h1>
      </div>
      <div class="mt-4 text-xl">
        <div class="mb-1">
          <%= link_to "法規", papers_path(current_user, exam_id1: 7,  exam_id2: 10), class: "border-bottom", method: :post, data: {confirm: "試験を開始しますか？"} %>
        </div>
        <div class="my-1">
          <%= link_to "基礎", papers_path(current_user, exam_id1: 8,  exam_id2: 11), class: "border-bottom", method: :post, data: {confirm: "試験を開始しますか？"} %>
        </div>
        <div class="my-1">
          <%= link_to "ガス技術", papers_path(current_user, exam_id1: 9,  exam_id2: 12), class: "border-bottom", method: :post, data: {confirm: "試験を開始しますか？"} %>
        </div>
      </div>
    </div>
  <br>
    <div>
      <div class="inline-block text-3xl">
        <h3>乙</h1>
      </div>
      <div class="mt-4 text-xl">
        <div class="my-1">
          <%= link_to "法規", papers_path(current_user, exam_id1: 1,  exam_id2: 4), class: "border-bottom", method: :post, data: {confirm: "試験を開始しますか？"} %>
        </div>
        <div class="my-1">
          <%= link_to "基礎", papers_path(current_user, exam_id1: 2,  exam_id2: 5), class: "border-bottom", method: :post, data: {confirm: "試験を開始しますか？"} %>
        </div>
        <div class="my-1">
          <%= link_to "ガス技術", papers_path(current_user, exam_id1: 3,  exam_id2: 6), class: "border-bottom", method: :post, data: {confirm: "試験を開始しますか？"} %>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>