config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update] do
    member do
      get :result
    end
  end
  resources :groups do
    collection do
      get :search
    end
    member do
      get :join
      delete :withdrawal
      delete :withdrawal_member
    end
  end
  resources :questions, only: %i[new]
  resources :password_resets, only: %i[new create edit update]
  resources :year_questions, only: %i[index]
  resources :category_questions, only: %i[index]
  resources :results, only: [:index, :show, :create]
  resources :contacts, only: [:new, :create]
  resources :question_papers, only: [:update]
  resources :papers do
    member do
      get :result
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :user

  has_many :question_papers, dependent: :destroy
  has_many :questions, through: :question_papers, dependent: :destroy
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  skip_before_action :require_login, only: %i[create]
  def create
    if logged_in?
      @paper = Paper.create(user_id: current_user.id)
    else
      @paper = Paper.create(user_id: 4)
    end
    # binding.pry
    if params[:exam_id1].to_i == 1 && params[:exam_id2].to_i == 2 && params[:exam_id3].to_i == 3
      a = Question.where(exam_id: 1).order("RANDOM()").limit(16)
      b = Question.where(exam_id: 2).order("RANDOM()").limit(10)
      c = Question.where(exam_id: 3).order("RANDOM()").limit(20)
      @questions = a + b + c
    elsif params[:exam_id1].to_i == 4 && params[:exam_id2].to_i == 5 && params[:exam_id3].to_i == 6
      a = Question.where(exam_id: 4).order("RANDOM()").limit(16)
      b = Question.where(exam_id: 5).order("RANDOM()").limit(10)
      c = Question.where(exam_id: 6).order("RANDOM()").limit(20)
      @questions = a + b + c
    elsif params[:exam_id1].to_i == 7 && params[:exam_id2].to_i == 8 && params[:exam_id3].to_i == 9
      a = Question.where(exam_id: 7).order("RANDOM()").limit(16)
      b = Question.where(exam_id: 8).order("RANDOM()").limit(10)
      c = Question.where(exam_id: 9).order("RANDOM()").limit(20)
      @questions = a + b + c
    elsif params[:exam_id1].to_i == 10 && params[:exam_id2].to_i == 11 && params[:exam_id3].to_i == 12
      a = Question.where(exam_id: 10).order("RANDOM()").limit(16)
      b = Question.where(exam_id: 11).order("RANDOM()").limit(10)
      c = Question.where(exam_id: 12).order("RANDOM()").limit(20)
      @questions = a + b + c
    elsif params[:exam_id1].to_i == 1 && params[:exam_id2].to_i == 4
      @questions = Question.where(exam_id: 1).or(Question.where(exam_id: 4)).order("RANDOM()").limit(16)
    elsif params[:exam_id1].to_i == 2 && params[:exam_id2].to_i == 5
      @questions = Question.where(exam_id: 2).or(Question.where(exam_id: 5)).order("RANDOM()").limit(10)
    elsif params[:exam_id1].to_i == 3 && params[:exam_id2].to_i == 6
      @questions = Question.where(exam_id: 3).or(Question.where(exam_id: 6)).order("RANDOM()").limit(20)
    elsif params[:exam_id1].to_i == 7 && params[:exam_id2].to_i == 10
      @questions = Question.where(exam_id: 7).or(Question.where(exam_id: 10)).order("RANDOM()").limit(16)
    elsif params[:exam_id1].to_i == 8 && params[:exam_id2].to_i == 11
      @questions = Question.where(exam_id: 8).or(Question.where(exam_id: 11)).order("RANDOM()").limit(10)
    elsif params[:exam_id1].to_i == 9 && params[:exam_id2].to_i == 12
      @questions = Question.where(exam_id: 9).or(Question.where(exam_id: 12)).order("RANDOM()").limit(20)
    elsif params[:exam_id1].to_i == 1
      @questions = Question.where(exam_id: 1).order("RANDOM()").limit(16)
    elsif params[:exam_id1].to_i == 2
      @questions = Question.where(exam_id: 2).order("RANDOM()").limit(10)
    elsif params[:exam_id1].to_i == 3
      @questions = Question.where(exam_id: 3).order("RANDOM()").limit(20)
    elsif params[:exam_id1].to_i == 4
      @questions = Question.where(exam_id: 4).order("RANDOM()").limit(16)
    elsif params[:exam_id1].to_i == 5
      @questions = Question.where(exam_id: 5).order("RANDOM()").limit(10)
    elsif params[:exam_id1].to_i == 6
      @questions = Question.where(exam_id: 6).order("RANDOM()").limit(20)
    elsif params[:exam_id1].to_i == 7
      @questions = Question.where(exam_id: 7).order("RANDOM()").limit(16)
    elsif params[:exam_id1].to_i == 8
      @questions = Question.where(exam_id: 8).order("RANDOM()").limit(10)
    elsif params[:exam_id1].to_i == 9
      @questions = Question.where(exam_id: 9).order("RANDOM()").limit(20)
    elsif params[:exam_id1].to_i == 10
      @questions = Question.where(exam_id: 10).order("RANDOM()").limit(16)
    elsif params[:exam_id1].to_i == 11
      @questions = Question.where(exam_id: 11).order("RANDOM()").limit(10)
    elsif params[:exam_id1].to_i == 12
      @questions = Question.where(exam_id: 12).order("RANDOM()").limit(20)
    end
    @questions.each do |question|
      QuestionPaper.create([{paper_id: @paper.id, question_id: question.id}])
    end
    redirect_to paper_path(@paper)
  end

  def show
    @paper = Paper.find(params[:id])
  end

  def result
    @paper = Paper.find(params[:id])
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_answer.html.erb
<% question.choices.each do |question_choice| %>
  <ul class="flex justify-center">
    <li class="mx-1">
      <%= link_to question_paper_path(choice_number: 1,question_paper_id: question_paper.id,question_id: question.id), method: :patch, remote: true, class: "text-white hover:text-white bg-green-500 btn" do %>
        <%= question_choice.choice1 %>
      <% end %>
    </li>
    <li class="mx-1">
      <%= link_to question_paper_path(choice_number: 2,question_paper_id: question_paper.id,question_id: question.id), method: :patch, remote: true, class: "text-white hover:text-white bg-green-500 btn" do%>
        <%= question_choice.choice2 %>
      <% end %>
    </li>
    <li class="mx-1">
      <%= link_to question_paper_path(choice_number: 3,question_paper_id: question_paper.id,question_id: question.id), method: :patch, remote: true, class: "text-white hover:text-white bg-green-500 btn" do%>
        <%= question_choice.choice3 %>
      <% end %>
    </li>
    <li class="mx-1">
      <%= link_to question_paper_path(choice_number: 4,question_paper_id: question_paper.id,question_id: question.id), method: :patch, remote: true, class: "text-white hover:text-white bg-green-500 btn" do%>
        <%= question_choice.choice4 %>
      <% end %>
    </li>
    <li class="mx-1">
      <%= link_to question_paper_path(choice_number: 5,question_paper_id: question_paper.id,question_id: question.id), method: :patch, remote: true, class: "text-white hover:text-white bg-green-500 btn" do%>
        <%= question_choice.choice5 %>
      <% end %>
    </li>
  </ul>
<% end %>

app/views/papers/result.html.erb
<div class="w-4/5 container mx-auto">
  <div class="text-center md:text-6xl text-4xl font-extrabold md:pr-12 md:mr-5"><h1 >最終結果</h1></div>
  <% @questions_all = 0 %>
  <% @question_houki_all = 0 %>
  <% @question_kiki_all = 0 %>
  <% @question_gijutu_all = 0 %>
  <% @question_trues = 0 %>
  <% @question_houki_trues = 0 %>
  <% @question_kiki_trues = 0 %>
  <% @question_gijutu_trues = 0 %>
  <% @paper.question_papers.each do |question_paper| %>
    <% if question_paper.question.exam_id.to_i == 1 && question_paper.judge != nil %>
      <% @question_houki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 4 && question_paper.judge != nil %>
      <% @question_houki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 7 && question_paper.judge != nil %>
      <% @question_houki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 10 && question_paper.judge != nil %>
      <% @question_houki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 2 && question_paper.judge != nil %>
      <% @question_kiki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 5 && question_paper.judge != nil %>
      <% @question_kiki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 8 && question_paper.judge != nil %>
      <% @question_kiki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 11 && question_paper.judge != nil %>
      <% @question_kiki_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 3 && question_paper.judge != nil %>
      <% @question_gijutu_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 6 && question_paper.judge != nil %>
      <% @question_gijutu_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 9 && question_paper.judge != nil %>
      <% @question_gijutu_all += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 12 && question_paper.judge != nil %>
      <% @question_gijutu_all += 1 %>
    <% end %>
    <% if question_paper.question.exam_id.to_i == 1 && question_paper.judge == true %>
      <% @question_houki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 4 && question_paper.judge == true %>
      <% @question_houki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 7 && question_paper.judge == true %>
      <% @question_houki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 10 && question_paper.judge == true %>
      <% @question_houki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 2 && question_paper.judge == true %>
      <% @question_kiki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 5 && question_paper.judge == true %>
      <% @question_kiki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 8 && question_paper.judge == true %>
      <% @question_kiki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 11 && question_paper.judge == true %>
      <% @question_kiki_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 3 && question_paper.judge == true %>
      <% @question_gijutu_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 6 && question_paper.judge == true %>
      <% @question_gijutu_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 9 && question_paper.judge == true %>
      <% @question_gijutu_trues += 1 %>
    <% elsif question_paper.question.exam_id.to_i == 12 && question_paper.judge == true %>
      <% @question_gijutu_trues += 1 %>
    <% end %>
    <% # binding.pry %>
  <% end %>
  <% @questions_all = @question_houki_all + @question_kiki_all + @question_gijutu_all %>
  <% @question_trues = @question_houki_trues + @question_kiki_trues + @question_gijutu_trues %>
  <br>
  <div class="text-center text-4xl font-bold md:pr-12 md:mr-5">
    <p>総合</p>
    <div class="text-center"><%= @question_trues %>/<%= @questions_all %></div>
    <div>(<%= (@question_trues.to_f/@questions_all.to_f*100).round(2) %>%)</div>
  </div>
  <br>
  <br>
  <br>
  <div class="flex justify-between text-3xl">
    <div>
      <p>法規</p>
      <div class="text-center"><%= @question_houki_trues %>/<%= @question_houki_all %></div>
    </div>
    <div>
      <p>基礎</p>
      <div class="text-center"><%= @question_kiki_trues %>/<%= @question_kiki_all %></div>
    </div>
    <div>
      <p>ガス技術</p>
      <div class="text-center"><%= @question_gijutu_trues %>/<%= @question_gijutu_all %></div>
    </div>
  </div>
  <br>
  <div class="text-center  md:pr-12 md:mr-5">
    <p class="md:text-4xl text-2xl">おつかれさまでした！！！</p>
    <br>
    <% if logged_in? %>
      <%= link_to "問題ホームへ", year_questions_path %>
    <% else %>
      <p class="text-xl">会員登録をしていただけますと過去に解いた模試結果を見返すことができます！</p>
      <p class="text-blue-500 border-solid border-b-2 inline-block"><%= link_to "会員登録ページへ", new_user_path %></p>
    <% end %>
  </div>
  <br>
</div>

app/views/papers/show.html.erb
<% @paper.question_papers.each.with_index(1) do |question_paper, i| %>
  <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl mb-1">
    <div class="md:flex">
      <div class="p-8">
        <p class="text-xl font-normal">問.<%= i %></p>
        <br>
        <div class="uppercase tracking-wide text-sm text-black font-semibold">
          <%= question_paper.question.sentence %>
        </div>
        <% if question_paper.question.id == 92 %>
          <%= image_tag 'q_kou_r2_g10.png' %>
        <% elsif question_paper.question.id == 30 %>
          <%= image_tag 'q_kou_r3_g12.png' %>
        <% elsif question_paper.question.id == 31 %>
          <%= image_tag 'q_kou_r3_g10-1.png' %>
        <% elsif question_paper.question.id == 197 %>
          <%= image_tag 'q_otsu_r3_g10-1.png' %>
        <% elsif question_paper.question.id == 18 %>
          <%= image_tag 'q_kou_r3_k5.png' %>
        <% end %>
        <% if question_paper.question.exception1.present? %>
          <p class="mt-2 text-black"><%= question_paper.question.exception1 %></p>
        <% end %>
        <% if question_paper.question.exception2.present? %>
          <p class="mt-2 text-black"><%= question_paper.question.exception2 %></p>
        <% end %>
        <% if question_paper.question.exception3.present? %>
          <p class="mt-2 text-black"><%= question_paper.question.exception3 %></p>
        <% end %>
        <% if question_paper.question.exception4.present? %>
          <p class="mt-2 text-black"><%= question_paper.question.exception4 %></p>
        <% end %>
        <% if question_paper.question.exception5.present? %>
          <p class="mt-2 text-black"><%= question_paper.question.exception5 %></p>
        <% end %>
        <% if question_paper.question.id == 31 %>
          <%= image_tag 'q_kou_r3_g10-2.png' %>
        <% elsif question_paper.question.id == 197 %>
          <%= image_tag 'q_otsu_r3_g10-2.png' %>
        <% end %>
        <div class="flex">
          <% if question_paper.question.supplement1.present? %>
            <p class="mt-2 text-black">(1)　<%= question_paper.question.supplement1 %></p>
          <% end %>
        </div>
        <div class="flex">
          <% if question_paper.question.supplement2.present? %>
            <p class="mt-2 text-black">(2)　<%= question_paper.question.supplement2 %></p>
          <% end %>
        </div>
        <div class="flex">
          <% if question_paper.question.supplement3.present? %>
            <p class="mt-2 text-black">(3)　<%= question_paper.question.supplement3 %></p>
          <% end %>
        </div>
        <div class="flex">
          <% if question_paper.question.supplement4.present? %>
            <p class="mt-2 text-black">(4)　<%= question_paper.question.supplement4 %></p>
          <% end %>
        </div>
        <div class="flex">
          <% if question_paper.question.supplement5.present? %>
            <p class="mt-2 text-black">(5)　<%= question_paper.question.supplement5 %></p>
          <% end %>
        </div>
        <% if question_paper.question.sub_sentence.present? %>
          <p class="mt-2 text-black">(イ)　<%= question_paper.question.sub_sentence %></p>
        <% end %>
        <% if question_paper.question.sub_sentence2.present? %>
          <p class="mt-2 text-black">(ロ)　<%= question_paper.question.sub_sentence2 %></p>
        <% end %>
        <% if question_paper.question.sub_sentence3.present? %>
          <p class="mt-2 text-black">(ハ)　<%= question_paper.question.sub_sentence3 %></p>
        <% end %>
        <% if question_paper.question.sub_sentence4.present? %>
          <p class="mt-2 text-black">(ニ)　<%= question_paper.question.sub_sentence4 %></p>
        <% end %>
        <% if question_paper.question.sub_sentence5.present? %>
          <p class="mt-2 text-black">(ホ)　<%= question_paper.question.sub_sentence5 %></p>
        <% end %>
        <% if question_paper.question.exception6.present? %>
          <p class="mt-2 text-black"><%= question_paper.question.exception6 %></p>
        <% end %>
        <br>
        <%= render partial: 'answer', locals: { question: question_paper.question, question_paper: question_paper } %>
        <div id="judge_<%= question_paper.id %>_<%= question_paper.question.id %>">
          <%= render partial: 'question_papers/judge', locals: { question: question_paper.question, question_paper: question_paper } %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<br>
<div class="text-center">
  <%= link_to '結果を見る', result_paper_path(@paper), class:"btn btn-primary"%>
</div>
<br>